version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.2.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.transport.ssl.enabled=false
      - xpack.security.http.ssl.enabled=false
    ports:
      - 9200:9200
      #- 9300:9300

  fluentd:
    build: ./fluentd
    user: root
    volumes:
      - ./fluentd/conf:/fluentd/etc
      - ./logs:/logs
    ports:
      - 8080:8080

  kibana:
    image: docker.elastic.co/kibana/kibana:8.2.0
    environment:
      ELASTICSEARCH_URL: https://elasticsearch:9200
    ports:
      - 5601:5601
